#####################################################################################################
"""Add superuser.

Revision ID: a94c970ba137
Revises: 06418e54240c
Create Date: 2024-06-13 08:12:26.355002+00:00

"""
#####################################################################################################

from collections.abc import Sequence
from typing import Final

from alembic.op import add_column, drop_column
from sqlalchemy import Boolean, Column, false as _sql_false

#####################################################################################################

# revision identifiers, used by Alembic.
# pylint: disable=invalid-name
revision: Final[str] = 'a94c970ba137'
down_revision: Final[str | None] = '06418e54240c'
branch_labels: Final[Sequence[str] | None] = None
depends_on: Final[str | None] = None
# pylint: enable=invalid-name

#####################################################################################################

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    add_column('users', Column('is_superuser', Boolean(), nullable=False, server_default=_sql_false()))
    # ### end Alembic commands ###

#####################################################################################################

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    drop_column('users', 'is_superuser')
    # ### end Alembic commands ###

#####################################################################################################
