#####################################################################################################
"""bind_conv_to_two_users

Revision ID: 92e150428401
Revises: e0fbac170f88
Create Date: 2024-09-25 11:51:37.322881+00:00

"""
#####################################################################################################

from collections.abc import Sequence
from typing import Final

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

#####################################################################################################

# revision identifiers, used by Alembic.
# pylint: disable=invalid-name
revision: Final[str] = '92e150428401'
down_revision: Final[str | None] = 'e0fbac170f88'
branch_labels: Final[Sequence[str] | None] = None
depends_on: Final[str | None] = None
# pylint: enable=invalid-name

#####################################################################################################

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('first_user_session', postgresql.UUID(), nullable=False))
    op.add_column('conversations', sa.Column('second_user_session', postgresql.UUID(), nullable=True))
    op.drop_constraint('fk_conversations_sessions_primary_uuid_session_id', 'conversations', type_='foreignkey')
    op.create_foreign_key('fk_conversations_sessions_primary_uuid_second_user_session', 'conversations', 'sessions', ['second_user_session'], ['primary_uuid'])
    op.create_foreign_key('fk_conversations_sessions_primary_uuid_first_user_session', 'conversations', 'sessions', ['first_user_session'], ['primary_uuid'])
    op.drop_column('conversations', 'session_id')
    op.drop_constraint('uq__users__login', 'users', type_='unique')
    op.create_unique_constraint('uc_users_login', 'users', ['login'])
    # ### end Alembic commands ###

#####################################################################################################

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_users_login', 'users', type_='unique')
    op.create_unique_constraint('uq__users__login', 'users', ['login'])
    op.add_column('conversations', sa.Column('session_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_conversations_sessions_primary_uuid_first_user_session', 'conversations', type_='foreignkey')
    op.drop_constraint('fk_conversations_sessions_primary_uuid_second_user_session', 'conversations', type_='foreignkey')
    op.create_foreign_key('fk_conversations_sessions_primary_uuid_session_id', 'conversations', 'sessions', ['session_id'], ['primary_uuid'])
    op.drop_column('conversations', 'second_user_session')
    op.drop_column('conversations', 'first_user_session')
    # ### end Alembic commands ###

#####################################################################################################
