services:

    ######################################################################################

    postgres:
        build:
            context: postgres/
            args:
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - USER_NAME=${USER_NAME}
        container_name: postgres
        networks:
            - private-network
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_INITDB_ARGS: -E 'UTF-8' --lc-collate='en_US.UTF-8' --lc-ctype='en_US.UTF-8'
        ports:
            - ${POSTGRES_PORT}:5432
        restart: unless-stopped
        volumes:
            - ${VOLUMES_PATH_POSTGRES}:/var/lib/postgresql/data

    ######################################################################################

#    pgadmin:
#        build:
#            context: pgadmin/
#            args:
#                - USER_ID=${USER_ID}
#                - GROUP_ID=${GROUP_ID}
#                - USER_NAME=${USER_NAME}
#        container_name: pgadmin
#        environment:
#            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#            PGADMIN_DEFAULT_PASSWORD: pgadmin
#            PGADMIN_DISABLE_POSTFIX: true
#            WAIT_HOSTS: postgres:5432
#        ports:
#            - 18888:80
#        networks:
#            - private-network
#        restart: unless-stopped
#        volumes:
#            - ${VOLUMES_PATH_PGADMIN}:/var/lib/pgadmin
#        depends_on:
#            - postgres
#        extra_hosts:
#            - "host.docker.internal:host-gateway"

    ######################################################################################

networks:
    private-network:
        driver: bridge

######################################################################################
